### ISSUE TITLE
AITalkAPI_Initが失敗する

### ISSUE THREAD

**Issue by nohararc** [Nkyoku/pyvcroid2#1]
リポジトリにあるsample.pyを参考に動かしてみましたが、
AITalkAPI_Initでエラーを吐いてしまいます。

以下のことを試しましたがいずれもうまくいきませんでした。
- 新たにvenvで仮想環境を切って再現
- Pythonを64bit版にして実行
- 管理者権限で実行
- OS再起動後実行

考えられる原因あればご教授いただければ幸いです。

## エラー
```
(temp) C:\Users\foo\Desktop\temp>python sample.py
Traceback (most recent call last):
  File "C:\Users\foo\Desktop\temp\sample.py", line 4, in <module>
    with pyvcroid2.VcRoid2(install_path=install_path, install_path_x86=install_path) as vc:
  File "C:\Users\foo\Desktop\temp\lib\site-packages\pyvcroid2\pyvcroid2.py", line 97, in __init__
    result = self.__dll.AITalkAPI_Init(config)
OSError: exception: access violation reading 0x0000AC50
```

## 再現コード(sample.pyの中身)
```
import pyvcroid2

install_path = "C:\Program Files (x86)\AHS\VOICEROID2"
with pyvcroid2.VcRoid2(install_path=install_path, install_path_x86=install_path) as vc:
    pass
```

## 環境
- OS: Win10 64bit
- Python: Python 3.9.1(32bit)
  - 64bit版Pythonだと`%1 は有効な Win32 アプリケーションではありません`というエラーでdllが読み込めませんでした
- VOICEROID2 : 2.0.1.0

P.S. voiceroid_daemon便利でいつも利用させてもらっています！

**Comment by Nkyoku** [comment]
32bit版と64bit版は引数の渡し方のデフォルトが違ったようなのでargtypesを指定するようにしました。
sample.pyが32bit、64bitどちらのPythonでも動作することを確認しました。

**Comment by nohararc** [comment]
ご対応ありがとうございます。
上記記載の環境で動作することを確認しました。

**Comment by uezo** [comment]
@Nkyoku いったんCloseとのことですが、私の環境では今のリポジトリをクローンしても状況が解消されませんでした。原因・対処方法わかりますでしょうか？

まず同梱の`sample.py`の実行結果です。`FileNotFoundError`となります。

```cmd
C:\pyvcroid2>python sample.py
Traceback (most recent call last):
  File "C:\pyvcroid2\sample.py", line 21, in <module>
    with pyvcroid2.VcRoid2() as vc:
  File "C:\pyvcroid2\pyvcroid2\pyvcroid2.py", line 70, in __init__
    self.__dll = windll.LoadLibrary(self.__install_path + "\\aitalked.dll")
  File "C:\Users\uezo\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\uezo\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Program Files\AHS\VOICEROID2\aitalked.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

続いて、以下の通り`sample2.py`（上の @nohararc さんのコードをベースに環境情報の表示を追加）を実行した結果は以下の通りです。` %1 は有効な Win32 アプリケーションではありません`となりました。

```cmd
C:\pyvcroid2>python sample2.py
OS: ('64bit', 'WindowsPE')
Pyhon: 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
Traceback (most recent call last):
  File "C:\pyvcroid2\sample2.py", line 9, in <module>
    with pyvcroid2.VcRoid2(install_path=install_path, install_path_x86=install_path) as vc:
  File "C:\pyvcroid2\pyvcroid2\pyvcroid2.py", line 70, in __init__
    self.__dll = windll.LoadLibrary(self.__install_path + "\\aitalked.dll")
  File "C:\Users\uezo\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\uezo\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 は有効な Win32 アプリケーションではありません。
```

# 再現コード

```python
import pyvcroid2
import platform
import sys

print(f"OS: {platform.architecture()}")
print(f"Pyhon: {sys.version}")

install_path = "C:\Program Files (x86)\AHS\VOICEROID2"
with pyvcroid2.VcRoid2(install_path=install_path, install_path_x86=install_path) as vc:
    pass
```

# 環境

- Python 3.10.1 (64bit)
- Windows 10.0.19042.1288 (64bit)
- VOICEROID 2.0.5.0 (aitalked.dllは5.0.3)

お手数ですが何卒、よろしくお願いします。
私もVOICEROID daemonありがたく使わせていただいております。素敵なツールをありがとうございます！！

**Comment by Nkyoku** [comment]
64bit版のPythonから32bit版のVOICEROID2のaitalk.dllを呼び出すことはできません。
AHSのマイページにログインしてVOICEROID2 64bit版 アップデータを入手してインストールしてください。
そうすれば使用できるようになります。

または32bit版のPythonでスクリプトを実行することでも解決可能です。

**Comment by uezo** [comment]
@Nkyoku 早速のご回答、ありがとうございます！！64bit Pythonから32bit DLLを呼び出せない・・・という記載をいくつかの記事で見かけたのですが、VOICEROIDが64bit版あるのを存じ上げていなかったのと、

> sample.pyが32bit、64bitどちらのPythonでも動作することを確認しました

を見て勝手に何らかの方法で64bit Pythonから32bit DLLをロードできるようになっている？と思い込んでおりました。
VOICEROIDを64bitにして試してみます。ありがとうございます。
