### ISSUE TITLE
loadLanguage()でエラー

### ISSUE THREAD

**Issue by nyanham** [Nkyoku/pyvcroid2#5]
32bitでは普通に実行できるのに、64bitでは、このエラーが起きます…

```Traceback (most recent call last):
  File "e:\Users\rafae\Documents\ツール\ボット\読み上げ\akane\main.py", line 51, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main.py", line 16, in main
    vc.loadLanguage(lang_list[1])
  File "C:\Users\rafae\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyvcroid2\pyvcroid2.py", line 174, in loadLanguage
    raise Exception(result)
Exception: ResultCode.READ_FAULT```

**Comment by U-Nano39** [comment]
32bitで動かしましょう。
